# Generated by Django 3.1.3 on 2020-12-07 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commodities_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Onion', 'Onion'), ('Garlic', 'Garlic'), ('Egg', 'Egg'), ('Potato', 'Potato'), ('Ginger', 'Ginger'), ('Maize', 'Maize'), ('Dry Chili', 'Dry Chili'), ('Termaric', 'Termaric'), ('Dates', 'Dates'), ('Milk Powder', 'Milk Powder'), ('Baby Food', 'Baby Food'), ('Cumin (Zira)', 'Cumin (Zira)'), ('Cardamom (Elachi)', 'Cardamom (Elachi)'), ('Cinnamon (Daruchini)', 'Cinnamon (Daruchini)'), ('Black Pepper (Gol marich)', 'Black Pepper (Gol marich)'), ('Cloves (Labanga)', 'Cloves (Labanga)'), ('Coriander (Dhania)', 'Coriander (Dhania'), ('Yellow Peas', 'Yellow Peas'), ('Cassia leaf (Tezpata)', 'Cassia leaf (Tezpata)'), ('Chola(Seed/Asto)', 'Chola(Seed/Asto)'), ('Cheak Peas', 'Cheak Peas'), ('Raw Salt', 'Raw Salt'), ('Refined Salt', 'Refined Salt'), ('Raw Sugar', 'Raw Sugar'), ('Refined Sugar', 'Refined Sugar'), ('Crude Soyabean', 'Crude Soyabean'), ('Refined Soyabean', 'Refined Soyabean'), ('Seed Soyabean', 'Seed Soyabean'), ('Crude palm Oil', 'Crude palm Oil'), ('Refined palm Oil', 'Refined palm Oil'), ('Seed palm Oil', 'Seed palm Oil'), ('Masur Dal', 'Masur Dal'), ('Chola Dal', 'Chola Dal'), ('Ankor Dal', 'Ankor Dal'), ('Mugh Dal', 'Mugh Dal'), ('Other Pulses', 'Other Pulses')], max_length=80)),
                ('production_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('production_place', models.CharField(max_length=150)),
                ('production_date', models.CharField(max_length=30)),
                ('insertion_time', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='commodities_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodities_ID', models.CharField(max_length=50, unique=True)),
                ('production_Code', models.CharField(max_length=50, null=True, unique=True)),
                ('import_Code', models.CharField(max_length=50, null=True, unique=True)),
                ('product_Name', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Onion', 'Onion'), ('Garlic', 'Garlic'), ('Egg', 'Egg'), ('Potato', 'Potato'), ('Ginger', 'Ginger'), ('Maize', 'Maize'), ('Dry Chili', 'Dry Chili'), ('Termaric', 'Termaric'), ('Dates', 'Dates'), ('Milk Powder', 'Milk Powder'), ('Baby Food', 'Baby Food'), ('Cumin (Zira)', 'Cumin (Zira)'), ('Cardamom (Elachi)', 'Cardamom (Elachi)'), ('Cinnamon (Daruchini)', 'Cinnamon (Daruchini)'), ('Black Pepper (Gol marich)', 'Black Pepper (Gol marich)'), ('Cloves (Labanga)', 'Cloves (Labanga)'), ('Coriander (Dhania)', 'Coriander (Dhania'), ('Yellow Peas', 'Yellow Peas'), ('Cassia leaf (Tezpata)', 'Cassia leaf (Tezpata)'), ('Chola(Seed/Asto)', 'Chola(Seed/Asto)'), ('Cheak Peas', 'Cheak Peas'), ('Raw Salt', 'Raw Salt'), ('Refined Salt', 'Refined Salt'), ('Raw Sugar', 'Raw Sugar'), ('Refined Sugar', 'Refined Sugar'), ('Crude Soyabean', 'Crude Soyabean'), ('Refined Soyabean', 'Refined Soyabean'), ('Seed Soyabean', 'Seed Soyabean'), ('Crude palm Oil', 'Crude palm Oil'), ('Refined palm Oil', 'Refined palm Oil'), ('Seed palm Oil', 'Seed palm Oil'), ('Masur Dal', 'Masur Dal'), ('Chola Dal', 'Chola Dal'), ('Ankor Dal', 'Ankor Dal'), ('Mugh Dal', 'Mugh Dal'), ('Other Pulses', 'Other Pulses')], max_length=80)),
                ('market_demand', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('market_consumption', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('current_stroage', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('unit_price', models.IntegerField()),
                ('wholeseller_price', models.IntegerField()),
                ('supplier_price', models.IntegerField()),
                ('international_price', models.IntegerField()),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('import_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('insertion_time', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='commodities_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Onion', 'Onion'), ('Garlic', 'Garlic'), ('Egg', 'Egg'), ('Potato', 'Potato'), ('Ginger', 'Ginger'), ('Maize', 'Maize'), ('Dry Chili', 'Dry Chili'), ('Termaric', 'Termaric'), ('Dates', 'Dates'), ('Milk Powder', 'Milk Powder'), ('Baby Food', 'Baby Food'), ('Cumin (Zira)', 'Cumin (Zira)'), ('Cardamom (Elachi)', 'Cardamom (Elachi)'), ('Cinnamon (Daruchini)', 'Cinnamon (Daruchini)'), ('Black Pepper (Gol marich)', 'Black Pepper (Gol marich)'), ('Cloves (Labanga)', 'Cloves (Labanga)'), ('Coriander (Dhania)', 'Coriander (Dhania'), ('Yellow Peas', 'Yellow Peas'), ('Cassia leaf (Tezpata)', 'Cassia leaf (Tezpata)'), ('Chola(Seed/Asto)', 'Chola(Seed/Asto)'), ('Cheak Peas', 'Cheak Peas'), ('Raw Salt', 'Raw Salt'), ('Refined Salt', 'Refined Salt'), ('Raw Sugar', 'Raw Sugar'), ('Refined Sugar', 'Refined Sugar'), ('Crude Soyabean', 'Crude Soyabean'), ('Refined Soyabean', 'Refined Soyabean'), ('Seed Soyabean', 'Seed Soyabean'), ('Crude palm Oil', 'Crude palm Oil'), ('Refined palm Oil', 'Refined palm Oil'), ('Seed palm Oil', 'Seed palm Oil'), ('Masur Dal', 'Masur Dal'), ('Chola Dal', 'Chola Dal'), ('Ankor Dal', 'Ankor Dal'), ('Mugh Dal', 'Mugh Dal'), ('Other Pulses', 'Other Pulses')], max_length=80)),
                ('import_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('import_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('import_place', models.CharField(max_length=150)),
                ('import_date', models.CharField(max_length=30)),
                ('importer_name', models.CharField(max_length=30)),
                ('importer_mobile_number', models.CharField(max_length=30)),
                ('insertion_time', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
