# Generated by Django 3.1.3 on 2020-12-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('national_id_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('organizations', models.CharField(choices=[('Ministry of Commerce', 'Commerce'), ('Ministry of Agriculture', 'Agriculture'), ('Bangladesh Bank', 'Bank'), ('Port Authority', 'Custom')], max_length=30)),
                ('organizational_role', models.CharField(max_length=30)),
                ('reference_email', models.EmailField(max_length=60, verbose_name='reference_email')),
                ('describtion', models.TextField(max_length=250)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_webadmin', models.BooleanField(default=False)),
                ('is_allow', models.BooleanField(default=False)),
                ('is_commerce', models.BooleanField(default=False)),
                ('is_agriculture', models.BooleanField(default=False)),
                ('is_bank', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
